import com.betomorrow.gradle.wording.domain.OutputFormat

plugins {
    id "com.betomorrow.gradle.wording"
}

wording {
    sheetId = "1UznpBPuRddr5gYPnRhNxkP-bcU0NHkhpTqi6B5V0QL0"
    keysColumn = "A"
    addMissingKeys = true
    outputFormat = OutputFormat.SPRING
    languages {
        'default' {
            column = "C"
        }
        'fr' {
            column = "D"
        }
    }
}
